# Generated by Django 4.1.7 on 2023-08-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0029_alter_order_created_by'),
        ('users', '0012_salesrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepCommissionCodeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_commission_code', models.FloatField(default=0.0, verbose_name='Product Commission Code')),
                ('sales_rep_commision', models.FloatField(default=0.0, verbose_name='Sales Rep Commission')),
                ('unit_sold', models.PositiveIntegerField(verbose_name='Unit Sold')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_report', to='order.orderedproduct')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_report', to='users.salesrep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
