# Generated by Django 4.1.7 on 2023-08-04 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0021_salesroute_company'),
        ('product', '0029_alter_product_re_order_mark'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepcommissioncodereport',
            name='sales_rep',
        ),
        migrations.RemoveField(
            model_name='salesrepcommissioncodereport',
            name='sales_rep_commision',
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_report', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_customers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='ml_tax',
            field=models.FloatField(default=0, verbose_name='Product ML Tax'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='report_product', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_cost_price',
            field=models.FloatField(default=0.0, verbose_name='Product Cost Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_label',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('textable', 'Textable'), ('free item', 'Free Item')], default='textable', max_length=10, verbose_name='Product Label'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_ml_quantity',
            field=models.FloatField(default=0, verbose_name='Product ML Quantity'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_retail_base_price',
            field=models.FloatField(default=0.0, verbose_name='Product Retail Base Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_retail_min_price',
            field=models.FloatField(default=0.0, verbose_name='Product Retail Min Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_sold_price',
            field=models.FloatField(default=0.0, verbose_name='Product Sold Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_wholesale_base_price',
            field=models.FloatField(default=0.0, verbose_name='Product Wholesale Base Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_wholesale_min_price',
            field=models.FloatField(default=0.0, verbose_name='Product Wholesale Min Price'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='total_sales_rep_commision',
            field=models.FloatField(default=0.0, verbose_name='Total Sales Rep Commission'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='unit_type',
            field=models.CharField(default='piece', max_length=50, verbose_name='Product Unit Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrepcommissioncodereport',
            name='unit_sold',
            field=models.PositiveIntegerField(verbose_name='Product Unit Sold'),
        ),
    ]
