# Generated by Django 4.1.7 on 2023-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_salesrepcommissioncodereport_sales_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='is_apply_ml',
            field=models.BooleanField(default=False, verbose_name='Is Apply ML Quantity'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='product_total_ml_quantity',
            field=models.FloatField(default=0, verbose_name='Total Product ML Quantity'),
        ),
        migrations.AddField(
            model_name='salesrepcommissioncodereport',
            name='total_sold_piece',
            field=models.IntegerField(default=1, verbose_name='Total Sold Piece'),
            preserve_default=False,
        ),
    ]
