# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_alter_customer_price_level_alter_customer_sales_rep_and_more'),
        ('reports', '0003_salesrepcommissioncodereport_is_apply_ml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepcommissioncodereport',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_customers', to='customers.customer'),
        ),
    ]
