# Generated by Django 4.1.7 on 2023-07-07 10:58

import app_modules.customers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendor_country_alter_vendor_office_number_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_name', models.CharField(max_length=50, verbose_name='Document Name')),
                ('document', models.FileField(upload_to='vendor-documents', validators=[app_modules.customers.validators.validate_file_extension], verbose_name='Document')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
