# Generated by Django 4.1.7 on 2023-07-12 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchaseorder_bill_number_and_more'),
        ('vendors', '0008_vendordocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50, verbose_name='Status')),
                ('bill_amount', models.FloatField(default=0.0, verbose_name='Bill Amount')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('due_amount', models.FloatField(default=0.0, verbose_name='Due Amount')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='purchase_order.purchaseorder', verbose_name='Purchase Order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bill', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_mode', models.CharField(choices=[('electronic transfer', 'Electronic Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit card', 'Credit Card'), ('money order', 'Money Order')], max_length=50, verbose_name='Payment Mode')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remark')),
                ('payment_amount', models.FloatField(default=0.0, verbose_name='Payment Amount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payment', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorPaymentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bill', to='vendors.vendorbill', verbose_name='Vendor Bill')),
                ('vendor_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payment', to='vendors.vendorpayment', verbose_name='Vendor Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
