# Generated by Django 4.1.7 on 2023-07-13 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorbill_vendorpayment_vendorpaymentbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Payment Amount'),
        ),
    ]
