# Generated by Django 4.1.7 on 2023-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_alter_vendorpayment_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_mode',
            field=models.CharField(choices=[('electronic transfer', 'Electronic Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit card', 'Credit Card'), ('money order', 'Money Order')], default='cash', max_length=50, verbose_name='Payment Mode'),
        ),
    ]
