# Generated by Django 4.1.7 on 2024-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_vendorpayment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpaymentbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
