# Generated by Django 4.1.7 on 2023-07-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_memo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditmemo",
            name="adjustment",
            field=models.FloatField(default=0, verbose_name="Adjustment"),
        ),
        migrations.AlterField(
            model_name="creditmemo",
            name="discount",
            field=models.FloatField(default=0, verbose_name="Discount"),
        ),
        migrations.AlterField(
            model_name="creditmemo",
            name="grand_total",
            field=models.FloatField(default=0, verbose_name="Grand Total"),
        ),
        migrations.AlterField(
            model_name="creditmemo",
            name="item_total",
            field=models.FloatField(default=0, verbose_name="Item Total"),
        ),
        migrations.AlterField(
            model_name="creditmemo",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="Remark"),
        ),
        migrations.AlterField(
            model_name="creditmemoproduct",
            name="damage_return_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Damage Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="creditmemoproduct",
            name="fresh_return_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Fresh Quantity"),
        ),
        migrations.AlterField(
            model_name="creditmemoproduct",
            name="return_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
