# Generated by Django 4.1.7 on 2023-07-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_warehouse_city_alter_warehouse_country_and_more"),
        ("credit_memo", "0002_alter_creditmemo_adjustment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditmemo",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_credit_memos",
                to="company.company",
                verbose_name="Company",
            ),
        ),
    ]
