# Generated by Django 4.1.7 on 2023-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_memo", "0003_alter_creditmemo_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditmemoproduct",
            name="total_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Total Price"),
        ),
    ]
