# Generated by Django 4.1.7 on 2023-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_memo", "0004_creditmemoproduct_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditmemoproduct",
            name="unit_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Unit Price"),
        ),
    ]
