# Generated by Django 4.1.7 on 2023-07-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credit_memo", "0005_creditmemoproduct_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditmemo",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
    ]
