# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0032_alter_csvfile_csv_file'),
        ('credit_memo', '0007_creditmemolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmemo',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='creditmemolog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Credit Memo'),
        ),
        migrations.AlterField(
            model_name='creditmemoproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_credit_memo', to='product.product'),
        ),
    ]
