# Generated by Django 4.1.7 on 2024-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_memo', '0008_alter_creditmemo_added_by_alter_creditmemolog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmemo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditmemolog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditmemoproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
