# Generated by Django 4.1.7 on 2023-07-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_alter_barcode_barcode_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("csv_file", models.FileField(upload_to="product-barcode")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
