# Generated by Django 4.1.7 on 2023-07-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_csvfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvfile",
            name="csv_file",
            field=models.FileField(upload_to="product-csv"),
        ),
    ]
