# Generated by Django 4.1.7 on 2023-07-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_alter_csvfile_csv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="box_upc",
        ),
        migrations.RemoveField(
            model_name="product",
            name="case_upc",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_upc",
        ),
    ]
