# Generated by Django 4.1.7 on 2023-07-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_warehouse_city_alter_warehouse_country_and_more"),
        ("product", "0027_productlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlog",
            name="affected_stock",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Affected Stock(Pieces)"
            ),
        ),
        migrations.AddField(
            model_name="productlog",
            name="before_stock",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Before Stock(Pieces)"
            ),
        ),
        migrations.AddField(
            model_name="productlog",
            name="stock",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Current Stock(Pieces)"
            ),
        ),
        migrations.AddField(
            model_name="productlog",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.warehouse",
                verbose_name="Warehouse",
            ),
        ),
    ]
