# Generated by Django 4.1.7 on 2023-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productlog_affected_stock_productlog_before_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='re_order_mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Re Order Mark (Pieces)'),
        ),
    ]
