# Generated by Django 4.1.7 on 2023-08-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_vendorpayment_payment_mode'),
        ('product', '0029_alter_product_re_order_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prefered_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='vendors.vendor', verbose_name='Prefered Vendor'),
        ),
    ]
