# Generated by Django 4.1.7 on 2023-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_prefered_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_unit',
            field=models.CharField(default=1, max_length=50, verbose_name='Item Unit'),
            preserve_default=False,
        ),
    ]
