# Generated by Django 4.1.7 on 2023-08-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_product_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(upload_to='csv'),
        ),
    ]
