# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_memo', '0008_alter_creditmemo_added_by_alter_creditmemolog_user_and_more'),
        ('company', '0013_alter_warehouse_company'),
        ('product', '0032_alter_csvfile_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='credit_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_memo.creditmemo', verbose_name='Credit Memo'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.warehouse', verbose_name='Warehouse'),
        ),
    ]
