# Generated by Django 4.1.7 on 2023-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productlog_action_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='commission_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prefered_vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='re_order_mark',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_min_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_min_price',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=0.0, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=0.0, verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_rate',
            field=models.FloatField(default=0.0, verbose_name='Retail  Rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Vehicle'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_rate',
            field=models.FloatField(default=0.0, verbose_name='Wholesale Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='srp',
            field=models.FloatField(blank=True, null=True, verbose_name='SRP(Suggested Retail Price)'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
