# Generated by Django 4.1.7 on 2024-06-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_product_genericname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Vehicle name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vehicle_set', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
