# Generated by Django 4.1.7 on 2024-06-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehicle',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vehicle_set', to='product.product'),
        ),
    ]
