# Generated by Django 4.1.7 on 2024-06-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productvehicle_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='productvehicle',
            name='product',
        ),
    ]
