# Generated by Django 4.1.7 on 2024-06-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_remove_product_vehicle_remove_productvehicle_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVehicle',
        ),
    ]
