# Generated by Django 4.1.7 on 2024-06-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_warehouse_company'),
        ('product', '0039_delete_productvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Vehicle name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vehicle_set', to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_set', to='product.productvehicle'),
        ),
    ]
