# Generated by Django 4.1.7 on 2024-06-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductstock',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_set', to='product.productvehicle'),
        ),
    ]
