# Generated by Django 4.1.7 on 2024-06-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_warehouseproductstock_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproductstock',
            name='vehicle',
        ),
    ]
