# Generated by Django 4.1.7 on 2024-06-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_warehouseproductstock_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproductstock',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='warehouseproductstockhistory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_history_set', to='product.productvehicle'),
        ),
    ]
