# Generated by Django 4.1.7 on 2024-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_remove_warehouseproductstock_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductstockhistory',
            name='ready_for_dispatched',
            field=models.PositiveIntegerField(default=0, verbose_name='Ready for Dispatched Stock(Pieces)'),
        ),
    ]
