# Generated by Django 4.1.7 on 2024-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_warehouseproductstockhistory_ready_for_dispatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproductstockhistory',
            name='ready_for_dispatched',
        ),
        migrations.AddField(
            model_name='warehouseproductstockhistory',
            name='ready_for_dispatch',
            field=models.PositiveIntegerField(default=0, verbose_name='Ready for Dispatch Stock(Pieces)'),
        ),
    ]
