# Generated by Django 4.1.7 on 2024-06-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_remove_warehouseproductstockhistory_ready_for_dispatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=0.0, verbose_name='Cost Price'),
        ),
    ]
