# Generated by Django 4.1.7 on 2024-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehicle',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Vehicle name'),
        ),
    ]
