# Generated by Django 4.1.7 on 2024-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_productvehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproductstockhistory',
            name='ready_for_dispatch',
        ),
        migrations.AddField(
            model_name='warehouseproductstock',
            name='ready_for_dispatch',
            field=models.PositiveIntegerField(default=0, verbose_name='Ready for Dispatch Stock(Pieces)'),
        ),
    ]
