# Generated by Django 4.1.7 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_warehouseproductstockhistory_ready_for_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='discount_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount A'),
        ),
        migrations.AddField(
            model_name='brand',
            name='discount_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount B'),
        ),
    ]
