# Generated by Django 4.1.7 on 2024-06-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_alter_brand_discount_a_alter_brand_discount_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='discount_a',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount A (%)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='discount_b',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount B (%)'),
        ),
    ]
