# Generated by Django 4.1.7 on 2023-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_image_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(null=True, upload_to='user profile'),
        ),
    ]
