# Generated by Django 4.1.7 on 2023-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default=1, upload_to='user profile'),
            preserve_default=False,
        ),
    ]
