# Generated by Django 4.1.7 on 2023-07-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver'),
        ('users', '0010_alter_user_image'),
    ]

    operations = [
    ]
