# Generated by Django 4.1.7 on 2023-08-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_0005_driver_0010_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
