# Generated by Django 4.1.7 on 2024-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('error', models.TextField(verbose_name='Error')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
