# Generated by Django 4.1.7 on 2024-06-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_managers'),
        ('users', '0014_errorlogs'),
    ]

    operations = [
    ]
