# Generated by Django 4.1.7 on 2023-06-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_cost_price_product_retail_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('item_total', models.FloatField(blank=True, null=True, verbose_name='Item Total')),
                ('overall_discount', models.FloatField(blank=True, null=True, verbose_name='Overall Discount')),
                ('shiping_charges', models.FloatField(blank=True, null=True, verbose_name='Shipping Charges')),
                ('grand_total', models.FloatField(blank=True, null=True, verbose_name='Grand Total')),
                ('is_saved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('unit_type', models.CharField(choices=[('box', 'Box'), ('piece', 'Piece'), ('case', 'Case')], default='piece', max_length=20, verbose_name='Unit Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('exchange', models.BooleanField(default=False)),
                ('textable', models.BooleanField(default=False)),
                ('free_item', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(verbose_name='Unit Price')),
                ('product_discount', models.FloatField(blank=True, null=True, verbose_name='Product Discount')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
