# Generated by Django 4.1.7 on 2023-07-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_pricelevelproduct_created_at_and_more'),
        ('order', '0003_alter_order_created_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('new', 'New'), ('packed', 'Packed'), ('ready to ship', 'Ready to Ship'), ('undelivered', 'Undelivered')], default='draft', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customers', to='customers.customer'),
        ),
    ]
