# Generated by Django 4.1.7 on 2023-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_is_saved_order_internal_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='unit_type',
            field=models.CharField(max_length=50, verbose_name='Unit Type'),
        ),
    ]
