# Generated by Django 4.1.7 on 2023-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderedproduct_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Grand Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('check', 'Check'), ('cash', 'Cash'), ('credit card', 'Credit Card'), ('money order', 'Money Order'), ('electronic transfer', 'Electronic Transfer')], max_length=30, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reference Id'),
        ),
    ]
