# Generated by Django 4.1.7 on 2023-07-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_paid_amount_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Paid Amount'),
        ),
    ]
