# Generated by Django 4.1.7 on 2023-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reference Number'),
        ),
    ]
