# Generated by Django 4.1.7 on 2023-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_adjustments_order_balance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('new', 'New'), ('packed', 'Packed'), ('ready to ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('undelivered', 'Undelivered'), ('cancel', 'Cancel'), ('close', 'Close')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
