# Generated by Django 4.1.7 on 2023-07-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_warehouse_city_alter_warehouse_country_and_more'),
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders', to='company.warehouse'),
        ),
    ]
