# Generated by Django 4.1.7 on 2023-07-13 05:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('car_nickname', models.CharField(max_length=30, verbose_name='Car Nick Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('licence_plate', models.CharField(max_length=20, verbose_name='Licence Plate')),
                ('start_mileage', models.CharField(max_length=50, verbose_name='Start Mileage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('make', models.CharField(max_length=30, verbose_name='Make')),
                ('vin_number', models.IntegerField(verbose_name='VIN Number')),
                ('inspect_exp_date', models.DateField(default=datetime.date.today, verbose_name='Inspect. Exp Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
