# Generated by Django 4.1.7 on 2023-07-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_car'),
        ('order', '0014_order_warehouse'),
    ]

    operations = [
    ]
