# Generated by Django 4.1.7 on 2023-07-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_merge_0014_car_0014_order_warehouse'),
        ('order', '0015_orderlog'),
    ]

    operations = [
    ]
