# Generated by Django 4.1.7 on 2023-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_order_use_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Billing Address"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shipping Address"
            ),
        ),
    ]
