# Generated by Django 4.1.7 on 2023-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_order_billing_address_order_shipping_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address line 1"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_city",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_country",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_state",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_zip_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zip Code"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_line_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 1 "
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2 "
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zip_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zip Code"),
        ),
    ]
