# Generated by Django 4.1.7 on 2023-07-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver'),
        ('order', '0018_driverassignedorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDriverRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Route Name')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assign_routes', to='users.driver', verbose_name='Assign Driver Routes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignOrderRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_driver_routes', to='order.assigndriverroutes', verbose_name='Assigned Driver Routes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assined_orders', to='order.order', verbose_name='Assigned Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
