# Generated by Django 4.1.7 on 2023-07-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_assigndriverroutes_assignorderroutes'),
        ('order', '0020_orderedproduct_packed_quantity_and_more'),
    ]

    operations = [
    ]
