# Generated by Django 4.1.7 on 2023-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0020_orderedproduct_packed_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="adjustments",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Adjustments"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="balance_amount",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Balance Amount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Grand Total"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Paid Amount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="use_credits",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Use Credits"
            ),
        ),
    ]
