# Generated by Django 4.1.7 on 2023-07-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_adjustments_alter_order_balance_amount_and_more'),
        ('order', '0022_assigndriverroutes_date_assignorderroutes_stop_and_more'),
    ]

    operations = [
    ]
