# Generated by Django 4.1.7 on 2023-07-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_warehouse_latitude_alter_warehouse_longitude'),
        ('users', '0011_merge_0005_driver_0010_alter_user_image'),
        ('order', '0024_car_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndriverroutes',
            name='start_location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='company.warehouse', verbose_name='Start Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigndriverroutes',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assign_routes', to='users.driver', verbose_name='Driver'),
        ),
    ]
