# Generated by Django 4.1.7 on 2023-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_assigndriverroutes_start_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndriverroutes',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
