# Generated by Django 4.1.7 on 2023-08-01 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0026_assigndriverroutes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created BY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ml_tax',
            field=models.FloatField(default=0, verbose_name='ML Tax'),
        ),
    ]
