# Generated by Django 4.1.7 on 2023-08-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_created_by_order_ml_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignorderroutes',
            name='remark',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='assigndriverroutes',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
