# Generated by Django 4.1.7 on 2023-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('packed', 'Packed'), ('ready to ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('undelivered', 'Undelivered'), ('cancel', 'Cancel')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
