# Generated by Django 4.1.7 on 2023-09-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_alter_customer_price_level_alter_customer_sales_rep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0013_alter_warehouse_company'),
        ('product', '0034_remove_subcategory_category_and_more'),
        ('order', '0031_alter_car_driver_alter_order_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='product_discount',
            new_name='product_discount2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ml_tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='overall_discount',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='free_item',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='textable',
        ),
        migrations.AddField(
            model_name='order',
            name='packing_charges',
            field=models.FloatField(blank=True, null=True, verbose_name='Packing Charges'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_discount1',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Discount 1'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_orders', to='company.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customers', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders', to='company.warehouse'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
    ]
