# Generated by Django 4.1.7 on 2023-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_rename_product_discount_orderedproduct_product_discount2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_reference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
