# Generated by Django 4.1.7 on 2024-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_car_driver_alter_order_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('packed', 'Packed'), ('ready to ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('undelivered', 'Undelivered'), ('cancel', 'Cancel'), ('ready for dispatch', 'Ready For Dispatch'), ('completed', 'Completed')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
