# Generated by Django 4.1.7 on 2024-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_alter_orderedproduct_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('cancel', 'Cancel'), ('ready for dispatch', 'Ready For Dispatch'), ('completed', 'Completed')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
