# Generated by Django 4.1.7 on 2024-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('check', 'Check'), ('cash', 'Cash'), ('upi/neft/rtgs', 'UPI/RTGS/NEFT')], max_length=30, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('print', 'Print'), ('new', 'New'), ('cancel', 'Cancel'), ('ready for dispatch', 'Ready For Dispatch'), ('completed', 'Completed')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
