# Generated by Django 4.1.7 on 2024-07-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0057_customer_credit_amount_and_more'),
        ('order', '0040_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50, verbose_name='Status')),
                ('bill_amount', models.FloatField(default=0.0, verbose_name='Bill Amount')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('due_amount', models.FloatField(default=0.0, verbose_name='Due Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
