# Generated by Django 4.1.7 on 2024-07-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_orderbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='slip_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Slip No'),
        ),
    ]
