# Generated by Django 4.1.7 on 2024-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_orderbill_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='case_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Case No'),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='checked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='gr_date',
            field=models.DateField(blank=True, null=True, verbose_name='G.R. Date'),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='gr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='packed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='transporter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='written_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
