# Generated by Django 4.1.7 on 2024-07-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_orderbill_case_number_orderbill_checked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbill',
            old_name='gr_no',
            new_name='gr_number',
        ),
    ]
