# Generated by Django 4.1.7 on 2024-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_rename_gr_no_orderbill_gr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generate', 'Generate'), ('new', 'New'), ('cancel', 'Cancel'), ('ready for dispatch', 'Ready For Dispatch'), ('completed', 'Completed')], default='new', max_length=25, verbose_name='Status'),
        ),
    ]
