# Generated by Django 4.1.7 on 2024-07-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_charges',
            new_name='shipping_charges',
        ),
    ]
