# Generated by Django 4.1.7 on 2024-07-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_alter_order_status'),
        ('order', '0049_order_is_bill_generated_alter_order_status'),
    ]

    operations = [
    ]
