# Generated by Django 4.1.7 on 2024-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_orderedproduct_free_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='free_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Free Quantity'),
        ),
    ]
