# Generated by Django 4.1.7 on 2024-07-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_orderedproduct_free_quantity_and_more'),
        ('order', '0051_alter_order_status'),
    ]

    operations = [
    ]
