# Generated by Django 4.1.7 on 2024-07-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_alter_orderedproduct_free_quantity'),
        ('order', '0052_merge_20240716_1448'),
    ]

    operations = [
    ]
