# Generated by Django 4.1.7 on 2024-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_merge_20240717_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='product_discount1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Discount 1'),
        ),
    ]
