# Generated by Django 4.1.7 on 2024-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_alter_orderedproduct_product_discount1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='product_discount2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Discount 2'),
        ),
    ]
