# Generated by Django 4.1.7 on 2024-07-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_merge_20240717_1214'),
        ('order', '0055_alter_orderedproduct_product_discount2'),
    ]

    operations = [
    ]
