# Generated by Django 4.1.7 on 2024-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_alter_orderedproduct_product_discount2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='sales-bills/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=30, null=True, verbose_name='Payment Method'),
        ),
    ]
