# Generated by Django 4.1.7 on 2024-07-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_merge_20240717_1409'),
        ('order', '0056_orderbill_pdf_file_alter_order_payment_method'),
    ]

    operations = [
    ]
