# Generated by Django 4.1.7 on 2024-07-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_merge_20240719_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbill',
            old_name='pdf_file',
            new_name='bill_pdf',
        ),
    ]
