# Generated by Django 4.1.7 on 2024-07-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_rename_pdf_file_orderbill_bill_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price_type',
            field=models.CharField(blank=True, choices=[('mrp', 'MRP'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='mrp', max_length=50, null=True, verbose_name='Price Type'),
        ),
    ]
