# Generated by Django 4.1.7 on 2024-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_orderedproduct_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bill Date'),
        ),
    ]
