# Generated by Django 4.1.7 on 2024-07-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_orderbill_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbill',
            old_name='bill_no',
            new_name='bill_id',
        ),
    ]
