# Generated by Django 4.1.7 on 2024-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_rename_bill_no_orderbill_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndriverroutes',
            name='synchronized_route',
            field=models.BooleanField(default=False),
        ),
    ]
