# Generated by Django 4.1.7 on 2024-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_rename_bill_no_orderbill_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbill',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Bill Amount'),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Due Amount'),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Paid Amount'),
        ),
    ]
