# Generated by Django 4.1.7 on 2024-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_order_inform_admin_for_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_replacement_completed',
            field=models.BooleanField(default=False, verbose_name='Is Replacement Completed'),
        ),
    ]
