# Generated by Django 4.1.7 on 2024-08-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_order_is_replacement_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_replacement_completed',
        ),
    ]
