# Generated by Django 4.1.7 on 2024-08-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_assigndriverroutes_synchronized_route'),
        ('order', '0067_remove_order_is_replacement_completed'),
    ]

    operations = [
    ]
