# Generated by Django 4.1.7 on 2024-08-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_merge_20240803_0412'),
        ('order', '0068_merge_20240805_0448'),
    ]

    operations = [
    ]
