# Generated by Django 4.1.7 on 2024-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_merge_20240805_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Unit Price'),
        ),
    ]
