# Generated by Django 4.1.7 on 2024-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_alter_orderedproduct_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbill',
            name='is_local_bill',
            field=models.BooleanField(default=True, verbose_name='Is Local Bill'),
        ),
    ]
