# Generated by Django 4.1.7 on 2024-08-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_merge_20240805_0558'),
        ('order', '0069_merge_20240805_0738'),
        ('order', '0070_orderbill_is_local_bill'),
    ]

    operations = [
    ]
