# Generated by Django 4.1.7 on 2023-07-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_status_alter_pricelevel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_level_customer', to='customers.pricelevel'),
        ),
    ]
