# Generated by Django 4.1.7 on 2023-07-10 10:21

import app_modules.customers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_price_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_line_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_line_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_longitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_suite_apartment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_zip_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='document',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address_line_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address_line_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_longitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_suite_apartment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_zip_code',
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 1')),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2')),
                ('shipping_suite_apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite/Apartment')),
                ('shipping_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('shipping_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('shipping_zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('shipping_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('shipping_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipping_address', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document', models.FileField(upload_to='customer documents', validators=[app_modules.customers.validators.validate_file_extension])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('billing_address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 1')),
                ('billing_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2')),
                ('billing_suite_apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite/Apartment')),
                ('billing_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('billing_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('billing_zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('billing_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('billing_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_address', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
