# Generated by Django 4.1.7 on 2023-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_remove_customer_billing_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbillingaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is Default'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is Default'),
        ),
    ]
