# Generated by Django 4.1.7 on 2023-07-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customerbillingaddress_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_address_line_1',
            field=models.CharField(default=1, max_length=100, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_city',
            field=models.CharField(default=1, max_length=20, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_country',
            field=models.CharField(default=1, max_length=20, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_state',
            field=models.CharField(default=1, max_length=20, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_address_line_1',
            field=models.CharField(default=1, max_length=100, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_city',
            field=models.CharField(default=1, max_length=20, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_country',
            field=models.CharField(default=1, max_length=20, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_state',
            field=models.CharField(default=1, max_length=20, verbose_name='State'),
            preserve_default=False,
        ),
    ]
