# Generated by Django 4.1.7 on 2023-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customerbillingaddress_billing_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocuments',
            name='document_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Document Name'),
            preserve_default=False,
        ),
    ]
