# Generated by Django 4.1.7 on 2023-07-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_car'),
        ('customers', '0015_alter_pricelevelproduct_custom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50, verbose_name='Status')),
                ('bill_amount', models.FloatField(default=0.0, verbose_name='Bill Amount')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('due_amount', models.FloatField(default=0.0, verbose_name='Due Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='customers.customerbill', verbose_name='Customer Bill')),
                ('customer_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='customers.payment', verbose_name='Customer Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
