# Generated by Django 4.1.7 on 2023-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customerbill_customerpaymentbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocuments',
            name='document_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Document Name'),
        ),
    ]
