# Generated by Django 4.1.7 on 2023-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customerlog'),
        ('customers', '0017_alter_customerdocuments_document_name'),
    ]

    operations = [
    ]
