# Generated by Django 4.1.7 on 2023-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_merge_20230717_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_credit_amount',
            field=models.FloatField(default=0, verbose_name='Total Credit Amount'),
        ),
    ]
