# Generated by Django 4.1.7 on 2023-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_merge_20230717_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('credit card', 'Credit Card'), ('money order', 'Money Order'), ('electronic transfer', 'Electronic Transfer')], default='cash', max_length=30, verbose_name='Payment Mode'),
        ),
    ]
