# Generated by Django 4.1.7 on 2023-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_payment_payment_mode'),
        ('customers', '0019_customer_total_credit_amount'),
    ]

    operations = [
    ]
