# Generated by Django 4.1.7 on 2023-08-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_salesroute_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('zone_code', models.CharField(max_length=50, verbose_name='Zone Code')),
                ('zone_description', models.TextField(verbose_name='Zone Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Customer Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cst',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CST Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='past_due_amount',
            field=models.FloatField(default=0, verbose_name='past_due_amount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='customer',
            name='transport',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='customerbillingaddress',
            name='billing_address_line_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 3'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='shipping_address_line_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_country',
            field=models.CharField(default='INDIA', max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_state',
            field=models.CharField(default='GUJARAT', max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='multiplecontact',
            name='contact_person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='multiplecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='multiplecontact',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='multiplecontact',
            name='type',
            field=models.CharField(blank=True, choices=[('store', 'Store'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.zone', verbose_name='Zone'),
        ),
    ]
