# Generated by Django 4.1.7 on 2023-08-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_zone_customer_area_customer_code_customer_cst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Store Close Time'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Store Open Time'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='terms',
            field=models.CharField(blank=True, choices=[('case', 'Case'), ('check', 'Check'), ('net 10', 'Net 10'), ('net 15', 'Net 15'), ('net 30', 'Net 30')], max_length=20, null=True, verbose_name='Terms'),
        ),
    ]
