# Generated by Django 4.1.7 on 2023-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_customer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_description',
            field=models.TextField(blank=True, null=True, verbose_name='Zone Description'),
        ),
    ]
