# Generated by Django 4.1.7 on 2023-08-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_alter_customer_email_alter_multiplecontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Code'),
        ),
    ]
