# Generated by Django 4.1.7 on 2023-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_alter_multiplecontact_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CST Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=255, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dba_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DBA Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='terms',
            field=models.CharField(blank=True, choices=[('case', 'Case'), ('check', 'Check'), ('net 10', 'Net 10'), ('net 15', 'Net 15'), ('net 30', 'Net 30')], max_length=255, null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='transport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transport'),
        ),
    ]
