# Generated by Django 4.1.7 on 2023-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_customer_area_alter_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
