# Generated by Django 4.1.7 on 2023-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_alter_customerbillingaddress_billing_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_country',
            field=models.CharField(default='INDIA', max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_state',
            field=models.CharField(default='GUJARAT', max_length=20, verbose_name='State'),
        ),
    ]
