# Generated by Django 4.1.7 on 2023-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_alter_customerbillingaddress_billing_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_address_line_1',
            field=models.CharField(max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_country',
            field=models.CharField(default='INDIA', max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_state',
            field=models.CharField(default='GUJARAT', max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_suite_apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite/Apartment'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_address_line_1',
            field=models.CharField(max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_address_line_3',
            field=models.CharField(blank=True, max_length=2550, null=True, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_country',
            field=models.CharField(default='INDIA', max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_state',
            field=models.CharField(default='GUJARAT', max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_suite_apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suite/Apartment'),
        ),
    ]
