# Generated by Django 4.1.7 on 2024-06-17 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_warehouse_company'),
        ('customers', '0033_alter_customer_price_level_alter_customer_sales_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_zone', to='company.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Shop Name'),
        ),
    ]
