# Generated by Django 4.1.7 on 2024-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_zone_company_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_billing_locked',
            field=models.BooleanField(default=False, verbose_name='Is Billing Locked'),
        ),
    ]
