# Generated by Django 4.1.7 on 2024-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0035_customer_is_billing_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('percent', models.FloatField(verbose_name='Percent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
