# Generated by Django 4.1.7 on 2024-06-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_vendorpayment_payment_mode'),
        ('customers', '0038_remove_customerdiscount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleVendorDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='customers.customer', verbose_name='Customer')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='customers.customerdiscount', verbose_name='Customer Discount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
