# Generated by Django 4.1.7 on 2024-06-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_alter_customerdiscount_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdiscount',
            name='vendor',
        ),
    ]
