# Generated by Django 4.1.7 on 2024-06-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_warehouseproductstockhistory_ready_for_dispatch_and_more'),
        ('company', '0013_alter_warehouse_company'),
        ('customers', '0042_remove_customerdiscount_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplevendordiscount',
            name='vendor',
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='product.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discounts', to='product.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discounts', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='multiplevendordiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='customers.customerdiscount', verbose_name='Discount'),
        ),
    ]
