# Generated by Django 4.1.7 on 2024-06-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_remove_multiplevendordiscount_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_billing_locked',
            new_name='is_locked',
        ),
    ]
