# Generated by Django 4.1.7 on 2024-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0044_rename_is_billing_locked_customer_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='discount_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount (%)'),
        ),
    ]
