# Generated by Django 4.1.7 on 2024-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_warehouseproductstockhistory_ready_for_dispatch_and_more'),
        ('company', '0013_alter_warehouse_company'),
        ('customers', '0045_multiplevendordiscount_discount_percent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDiscount',
            new_name='Discount',
        ),
    ]
