# Generated by Django 4.1.7 on 2024-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0046_rename_customerdiscount_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='additional_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Additional Discount (%)'),
        ),
        migrations.AlterField(
            model_name='multiplevendordiscount',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount (%)'),
        ),
    ]
