# Generated by Django 4.1.7 on 2024-06-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0047_multiplevendordiscount_additional_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
