# Generated by Django 4.1.7 on 2024-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0048_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Customer Code'),
        ),
    ]
