# Generated by Django 4.1.7 on 2024-06-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0049_alter_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Lock Status'),
        ),
    ]
