# Generated by Django 4.1.7 on 2024-06-26 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0038_alter_orderedproduct_unit_type'),
        ('customers', '0050_alter_customer_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Amount')),
                ('return_type', models.CharField(choices=[('money', 'Money'), ('credit', 'Credit')], max_length=25, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created BY')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_customers', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_orders', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='billing_suite_apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='shipping_suite_apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 3'),
        ),
        migrations.CreateModel(
            name='ReplacementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('replace_quantity', models.PositiveIntegerField(verbose_name='Replace Quantity')),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_order_products', to='order.orderedproduct')),
                ('replacement_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_order_products', to='customers.replacement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
