# Generated by Django 4.1.7 on 2024-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0051_replacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='replace_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Replace ID'),
        ),
    ]
