# Generated by Django 4.1.7 on 2024-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0051_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='return_type',
            field=models.CharField(choices=[('money', 'Money'), ('credit', 'Credit')], max_length=25, verbose_name='Return Type'),
        ),
    ]
