# Generated by Django 4.1.7 on 2024-06-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0052_replacement_replace_id_alter_replacement_return_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='total_amount',
        ),
    ]
