# Generated by Django 4.1.7 on 2024-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0053_remove_replacement_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Name'),
        ),
    ]
