# Generated by Django 4.1.7 on 2024-06-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0054_customer_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplevendordiscount',
            name='additional_discount',
        ),
        migrations.RemoveField(
            model_name='multiplevendordiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='multiplevendordiscount',
            name='discount_percent',
        ),
    ]
