# Generated by Django 4.1.7 on 2024-06-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0055_remove_multiplevendordiscount_additional_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='additional_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_secondary_discounts', to='customers.discount'),
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='additional_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Additional Discount (%)'),
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='primary_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_primary_discounts', to='customers.discount'),
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='primary_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Primary Discount (%)'),
        ),
    ]
