# Generated by Django 4.1.7 on 2024-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0056_multiplevendordiscount_additional_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_amount',
            field=models.FloatField(default=0, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='past_due_amount',
            field=models.FloatField(default=0, verbose_name='Past Due Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('upi/neft/rtgs', 'UPI/NEFT/RTGS')], default='cash', max_length=30, verbose_name='Payment Mode'),
        ),
    ]
