# Generated by Django 4.1.7 on 2024-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0052_replacement_replace_id'),
        ('customers', '0057_customer_credit_amount_and_more'),
    ]

    operations = [
    ]
