# Generated by Django 4.1.7 on 2024-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0058_merge_20240703_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('check', 'Cheque'), ('cash', 'Cash'), ('upi/neft/rtgs', 'UPI/NEFT/RTGS')], default='cash', max_length=30, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Id'),
        ),
    ]
