# Generated by Django 4.1.7 on 2024-07-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0059_alter_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacement',
            name='replace_id',
        ),
    ]
