# Generated by Django 4.1.7 on 2024-07-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0060_remove_replacement_replace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='replace_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Replace ID'),
        ),
    ]
