# Generated by Django 4.1.7 on 2024-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0061_replacement_replace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpaymentbill',
            name='customer_bill',
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='is_primary_brand_discount',
            field=models.BooleanField(default=False, verbose_name='Is Primary Brand Discount'),
        ),
        migrations.AddField(
            model_name='multiplevendordiscount',
            name='is_secondary_brand_discount',
            field=models.BooleanField(default=False, verbose_name='Is Secondary Brand Discount'),
        ),
    ]
