# Generated by Django 4.1.7 on 2024-07-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_alter_order_status'),
        ('customers', '0062_remove_customerpaymentbill_customer_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentbill',
            name='customer_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='order.orderbill', verbose_name='Order Bill'),
        ),
    ]
