# Generated by Django 4.1.7 on 2024-08-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0065_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='settlement_completed',
            field=models.BooleanField(default=False, verbose_name='Settlement Completed'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='settlement_pending',
            field=models.BooleanField(default=False, verbose_name='Settlement Pending'),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='return_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('settlement', 'Settlement')], max_length=25, verbose_name='Return Type'),
        ),
    ]
