# Generated by Django 4.1.7 on 2024-08-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_alter_assigndriverroutes_updated_at_and_more'),
        ('customers', '0066_replacement_settlement_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_orders', to='order.order', verbose_name='Order'),
        ),
    ]
