# Generated by Django 4.1.7 on 2023-07-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_warehouse_city_alter_warehouse_country_and_more"),
        ("purchase_order", "0005_alter_purchaseorder_bill_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.warehouse",
                verbose_name="Warehouse",
            ),
        ),
    ]
