# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productlog_action_by_and_more'),
        ('company', '0013_alter_warehouse_company'),
        ('purchase_order', '0006_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_purchase_order', to='product.product'),
        ),
    ]
