# Generated by Django 4.1.7 on 2024-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_alter_purchaseorder_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
