# Generated by Django 4.1.7 on 2024-07-29 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpanseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('budget_amount', models.FloatField(default=0.0, verbose_name='Budget Amount')),
                ('actual_amount', models.FloatField(default=0.0, verbose_name='Actual Amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Exapnse Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Expanse Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
