# Generated by Django 4.1.7 on 2024-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansemanagement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expansemanagement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
