# Generated by Django 4.1.7 on 2024-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0002_remove_expansemanagement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansemanagement',
            name='expanse',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
