# Generated by Django 4.1.7 on 2024-07-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0003_expansemanagement_expanse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expansemanagement',
            old_name='notes',
            new_name='note',
        ),
    ]
