# Generated by Django 4.1.7 on 2024-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0004_rename_notes_expansemanagement_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansemanagement',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='expanse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
