# Generated by Django 4.1.7 on 2024-07-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0006_expansecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expansemanagement',
            old_name='budget_amount',
            new_name='expanse_budget',
        ),
    ]
