# Generated by Django 4.1.7 on 2024-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_warehouse_company'),
        ('expanse_management', '0007_rename_budget_amount_expansemanagement_expanse_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_category', to='company.company'),
        ),
    ]
