# Generated by Django 4.1.7 on 2024-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0008_expansecategory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansemanagement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
