# Generated by Django 4.1.7 on 2024-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0009_alter_expansemanagement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansebudget',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
