# Generated by Django 4.1.7 on 2024-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_management', '0010_alter_expansebudget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansebudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expansecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expansemanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
