# Generated by Django 4.1.7 on 2023-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_warehouse_city_alter_warehouse_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="latitude",
            field=models.FloatField(
                blank=True, max_length=100, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="longitude",
            field=models.FloatField(
                blank=True, max_length=100, null=True, verbose_name="Longitude"
            ),
        ),
    ]
