# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_address_line_1_company_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.company'),
        ),
    ]
